version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security features including authentication
      - xpack.security.audit.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - es_network
  search:
    build: ./search_app
    container_name: search_app
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - es_network
volumes:
  es_data:
    driver: local

networks:
  es_network:
    driver: bridge
